Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "requestedUUID"
          "AttributeType": "S"
        - "AttributeName": "userRequest"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "requestedUUID"
          "KeyType": "HASH"
        - "AttributeName": "userRequest"
          "KeyType": "RANGE"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "NotificationTable"
